framework:
    profiler:
        only_exceptions: false
    cache:
        app: cache.adapter.array
        system: cache.adapter.system
        directory: '%kernel.cache_dir%/pools'
        default_doctrine_dbal_provider: 'doctrine.system_cache_pool'
